server:
  port: 8081
  servlet:
    context-path: /auth

logging.level.org.springframework: DEBUG

spring:
  application:
    name: qx-auth-sso
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/

# 注册中心配置
eureka:
  instance:
    instance-id: qx-auth-sso-${server.port}
    # prefer-ip-address: true     #访问路径可以显示IP地址
  client:
    service-url:
      defaultZone: http://qx:qx@localhost:7001/eureka/
