---
spring:
  profiles: 9999
  redis:
    password:
    host: 10.0.75.1
    timeout: 5000
server:
  port: 9991

---
spring:
  profiles: 9998
  redis:
    password:
    host: 10.0.75.1
    timeout: 5000
server:
  port: 9998

---
spring:
  profiles: 9997
  redis:
    password:
    host: 10.0.75.1
    timeout: 5000
server:
  port: 9997
