# 数据源
spring:
  datasource:
    url: jdbc:mysql://123.207.242.177:3306/qx-test?useSSL=false&&serverTimezone=GMT%2B8
    username: root
    password: root
    #使用阿里的druid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

###################  Mybatis配置  ###################
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
