// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

package com.qianxun.auth.grpc.login;

public final class Login {
  private Login() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qianxun_auth_grpc_login_LoginReq_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_qianxun_auth_grpc_login_LoginReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qianxun_auth_grpc_login_LoginRes_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_qianxun_auth_grpc_login_LoginRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013Login.proto\022\033com.qianxun.auth.grpc.log" +
      "in\"-\n\010LoginReq\022\017\n\007account\030\001 \001(\t\022\020\n\010passw" +
      "ord\030\002 \001(\t\"\033\n\010LoginRes\022\017\n\007message\030\001 \001(\t2e" +
      "\n\014LoginService\022U\n\005login\022%.com.qianxun.au" +
      "th.grpc.login.LoginReq\032%.com.qianxun.aut" +
      "h.grpc.login.LoginResB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_qianxun_auth_grpc_login_LoginReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_qianxun_auth_grpc_login_LoginReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_qianxun_auth_grpc_login_LoginReq_descriptor,
        new String[] { "Account", "Password", });
    internal_static_com_qianxun_auth_grpc_login_LoginRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_qianxun_auth_grpc_login_LoginRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_qianxun_auth_grpc_login_LoginRes_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
