// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

package com.qianxun.auth.grpc.login;

public interface LoginReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.qianxun.auth.grpc.login.LoginReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string account = 1;</code>
   */
  String getAccount();
  /**
   * <code>string account = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccountBytes();

  /**
   * <code>string password = 2;</code>
   */
  String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
