// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

package com.qianxun.auth.grpc.login;

public interface LoginResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.qianxun.auth.grpc.login.LoginRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
