server: 
  port: 8888
  
spring:
  application:
    name:  qx-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cloudslife/qx-config.git
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
