// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth_user.proto

package com.qianxun.grpc.lib.authUser;

public final class AuthUserOuterClass {
  private AuthUserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ByAccountReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:authUser.ByAccountReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string account = 1;</code>
     */
    java.lang.String getAccount();
    /**
     * <code>string account = 1;</code>
     */
    com.google.protobuf.ByteString
        getAccountBytes();
  }
  /**
   * Protobuf type {@code authUser.ByAccountReq}
   */
  public  static final class ByAccountReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:authUser.ByAccountReq)
      ByAccountReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ByAccountReq.newBuilder() to construct.
    private ByAccountReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ByAccountReq() {
      account_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ByAccountReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              account_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qianxun.grpc.lib.authUser.AuthUserOuterClass.internal_static_authUser_ByAccountReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qianxun.grpc.lib.authUser.AuthUserOuterClass.internal_static_authUser_ByAccountReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq.class, com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq.Builder.class);
    }

    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private volatile java.lang.Object account_;
    /**
     * <code>string account = 1;</code>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        account_ = s;
        return s;
      }
    }
    /**
     * <code>string account = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAccountBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, account_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAccountBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, account_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq)) {
        return super.equals(obj);
      }
      com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq other = (com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq) obj;

      if (!getAccount()
          .equals(other.getAccount())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAccount().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code authUser.ByAccountReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:authUser.ByAccountReq)
        com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qianxun.grpc.lib.authUser.AuthUserOuterClass.internal_static_authUser_ByAccountReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qianxun.grpc.lib.authUser.AuthUserOuterClass.internal_static_authUser_ByAccountReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq.class, com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq.Builder.class);
      }

      // Construct using com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        account_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qianxun.grpc.lib.authUser.AuthUserOuterClass.internal_static_authUser_ByAccountReq_descriptor;
      }

      @java.lang.Override
      public com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq getDefaultInstanceForType() {
        return com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq build() {
        com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq buildPartial() {
        com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq result = new com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq(this);
        result.account_ = account_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq) {
          return mergeFrom((com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq other) {
        if (other == com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq.getDefaultInstance()) return this;
        if (!other.getAccount().isEmpty()) {
          account_ = other.account_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object account_ = "";
      /**
       * <code>string account = 1;</code>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string account = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string account = 1;</code>
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string account = 1;</code>
       */
      public Builder clearAccount() {
        
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>string account = 1;</code>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        account_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:authUser.ByAccountReq)
    }

    // @@protoc_insertion_point(class_scope:authUser.ByAccountReq)
    private static final com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq();
    }

    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ByAccountReq>
        PARSER = new com.google.protobuf.AbstractParser<ByAccountReq>() {
      @java.lang.Override
      public ByAccountReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ByAccountReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ByAccountReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ByAccountReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.qianxun.grpc.lib.authUser.AuthUserOuterClass.ByAccountReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AuthUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:authUser.AuthUser)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string permissions = 1;</code>
     */
    java.util.List<java.lang.String>
        getPermissionsList();
    /**
     * <code>repeated string permissions = 1;</code>
     */
    int getPermissionsCount();
    /**
     * <code>repeated string permissions = 1;</code>
     */
    java.lang.String getPermissions(int index);
    /**
     * <code>repeated string permissions = 1;</code>
     */
    com.google.protobuf.ByteString
        getPermissionsBytes(int index);

    /**
     * <code>repeated int32 roles = 2;</code>
     */
    java.util.List<java.lang.Integer> getRolesList();
    /**
     * <code>repeated int32 roles = 2;</code>
     */
    int getRolesCount();
    /**
     * <code>repeated int32 roles = 2;</code>
     */
    int getRoles(int index);

    /**
     * <code>int32 dept_id = 3;</code>
     */
    int getDeptId();

    /**
     * <code>int32 id = 4;</code>
     */
    int getId();

    /**
     * <code>string password_encrypted = 5;</code>
     */
    java.lang.String getPasswordEncrypted();
    /**
     * <code>string password_encrypted = 5;</code>
     */
    com.google.protobuf.ByteString
        getPasswordEncryptedBytes();

    /**
     * <code>int32 locked = 6;</code>
     */
    int getLocked();
  }
  /**
   * Protobuf type {@code authUser.AuthUser}
   */
  public  static final class AuthUser extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:authUser.AuthUser)
      AuthUserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AuthUser.newBuilder() to construct.
    private AuthUser(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AuthUser() {
      permissions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      roles_ = emptyIntList();
      passwordEncrypted_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AuthUser(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                permissions_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              permissions_.add(s);
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                roles_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              roles_.addInt(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                roles_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                roles_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {

              deptId_ = input.readInt32();
              break;
            }
            case 32: {

              id_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              passwordEncrypted_ = s;
              break;
            }
            case 48: {

              locked_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          permissions_ = permissions_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          roles_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qianxun.grpc.lib.authUser.AuthUserOuterClass.internal_static_authUser_AuthUser_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qianxun.grpc.lib.authUser.AuthUserOuterClass.internal_static_authUser_AuthUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser.class, com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser.Builder.class);
    }

    private int bitField0_;
    public static final int PERMISSIONS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList permissions_;
    /**
     * <code>repeated string permissions = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPermissionsList() {
      return permissions_;
    }
    /**
     * <code>repeated string permissions = 1;</code>
     */
    public int getPermissionsCount() {
      return permissions_.size();
    }
    /**
     * <code>repeated string permissions = 1;</code>
     */
    public java.lang.String getPermissions(int index) {
      return permissions_.get(index);
    }
    /**
     * <code>repeated string permissions = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPermissionsBytes(int index) {
      return permissions_.getByteString(index);
    }

    public static final int ROLES_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList roles_;
    /**
     * <code>repeated int32 roles = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getRolesList() {
      return roles_;
    }
    /**
     * <code>repeated int32 roles = 2;</code>
     */
    public int getRolesCount() {
      return roles_.size();
    }
    /**
     * <code>repeated int32 roles = 2;</code>
     */
    public int getRoles(int index) {
      return roles_.getInt(index);
    }
    private int rolesMemoizedSerializedSize = -1;

    public static final int DEPT_ID_FIELD_NUMBER = 3;
    private int deptId_;
    /**
     * <code>int32 dept_id = 3;</code>
     */
    public int getDeptId() {
      return deptId_;
    }

    public static final int ID_FIELD_NUMBER = 4;
    private int id_;
    /**
     * <code>int32 id = 4;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int PASSWORD_ENCRYPTED_FIELD_NUMBER = 5;
    private volatile java.lang.Object passwordEncrypted_;
    /**
     * <code>string password_encrypted = 5;</code>
     */
    public java.lang.String getPasswordEncrypted() {
      java.lang.Object ref = passwordEncrypted_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        passwordEncrypted_ = s;
        return s;
      }
    }
    /**
     * <code>string password_encrypted = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordEncryptedBytes() {
      java.lang.Object ref = passwordEncrypted_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        passwordEncrypted_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCKED_FIELD_NUMBER = 6;
    private int locked_;
    /**
     * <code>int32 locked = 6;</code>
     */
    public int getLocked() {
      return locked_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < permissions_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, permissions_.getRaw(i));
      }
      if (getRolesList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(rolesMemoizedSerializedSize);
      }
      for (int i = 0; i < roles_.size(); i++) {
        output.writeInt32NoTag(roles_.getInt(i));
      }
      if (deptId_ != 0) {
        output.writeInt32(3, deptId_);
      }
      if (id_ != 0) {
        output.writeInt32(4, id_);
      }
      if (!getPasswordEncryptedBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, passwordEncrypted_);
      }
      if (locked_ != 0) {
        output.writeInt32(6, locked_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < permissions_.size(); i++) {
          dataSize += computeStringSizeNoTag(permissions_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPermissionsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < roles_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(roles_.getInt(i));
        }
        size += dataSize;
        if (!getRolesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        rolesMemoizedSerializedSize = dataSize;
      }
      if (deptId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, deptId_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, id_);
      }
      if (!getPasswordEncryptedBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, passwordEncrypted_);
      }
      if (locked_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, locked_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser)) {
        return super.equals(obj);
      }
      com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser other = (com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser) obj;

      if (!getPermissionsList()
          .equals(other.getPermissionsList())) return false;
      if (!getRolesList()
          .equals(other.getRolesList())) return false;
      if (getDeptId()
          != other.getDeptId()) return false;
      if (getId()
          != other.getId()) return false;
      if (!getPasswordEncrypted()
          .equals(other.getPasswordEncrypted())) return false;
      if (getLocked()
          != other.getLocked()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPermissionsCount() > 0) {
        hash = (37 * hash) + PERMISSIONS_FIELD_NUMBER;
        hash = (53 * hash) + getPermissionsList().hashCode();
      }
      if (getRolesCount() > 0) {
        hash = (37 * hash) + ROLES_FIELD_NUMBER;
        hash = (53 * hash) + getRolesList().hashCode();
      }
      hash = (37 * hash) + DEPT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDeptId();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + PASSWORD_ENCRYPTED_FIELD_NUMBER;
      hash = (53 * hash) + getPasswordEncrypted().hashCode();
      hash = (37 * hash) + LOCKED_FIELD_NUMBER;
      hash = (53 * hash) + getLocked();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code authUser.AuthUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:authUser.AuthUser)
        com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qianxun.grpc.lib.authUser.AuthUserOuterClass.internal_static_authUser_AuthUser_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qianxun.grpc.lib.authUser.AuthUserOuterClass.internal_static_authUser_AuthUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser.class, com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser.Builder.class);
      }

      // Construct using com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        permissions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        roles_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        deptId_ = 0;

        id_ = 0;

        passwordEncrypted_ = "";

        locked_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qianxun.grpc.lib.authUser.AuthUserOuterClass.internal_static_authUser_AuthUser_descriptor;
      }

      @java.lang.Override
      public com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser getDefaultInstanceForType() {
        return com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser.getDefaultInstance();
      }

      @java.lang.Override
      public com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser build() {
        com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser buildPartial() {
        com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser result = new com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          permissions_ = permissions_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.permissions_ = permissions_;
        if (((bitField0_ & 0x00000002) != 0)) {
          roles_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.roles_ = roles_;
        result.deptId_ = deptId_;
        result.id_ = id_;
        result.passwordEncrypted_ = passwordEncrypted_;
        result.locked_ = locked_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser) {
          return mergeFrom((com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser other) {
        if (other == com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser.getDefaultInstance()) return this;
        if (!other.permissions_.isEmpty()) {
          if (permissions_.isEmpty()) {
            permissions_ = other.permissions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePermissionsIsMutable();
            permissions_.addAll(other.permissions_);
          }
          onChanged();
        }
        if (!other.roles_.isEmpty()) {
          if (roles_.isEmpty()) {
            roles_ = other.roles_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRolesIsMutable();
            roles_.addAll(other.roles_);
          }
          onChanged();
        }
        if (other.getDeptId() != 0) {
          setDeptId(other.getDeptId());
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getPasswordEncrypted().isEmpty()) {
          passwordEncrypted_ = other.passwordEncrypted_;
          onChanged();
        }
        if (other.getLocked() != 0) {
          setLocked(other.getLocked());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList permissions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePermissionsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          permissions_ = new com.google.protobuf.LazyStringArrayList(permissions_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string permissions = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPermissionsList() {
        return permissions_.getUnmodifiableView();
      }
      /**
       * <code>repeated string permissions = 1;</code>
       */
      public int getPermissionsCount() {
        return permissions_.size();
      }
      /**
       * <code>repeated string permissions = 1;</code>
       */
      public java.lang.String getPermissions(int index) {
        return permissions_.get(index);
      }
      /**
       * <code>repeated string permissions = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPermissionsBytes(int index) {
        return permissions_.getByteString(index);
      }
      /**
       * <code>repeated string permissions = 1;</code>
       */
      public Builder setPermissions(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePermissionsIsMutable();
        permissions_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string permissions = 1;</code>
       */
      public Builder addPermissions(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePermissionsIsMutable();
        permissions_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string permissions = 1;</code>
       */
      public Builder addAllPermissions(
          java.lang.Iterable<java.lang.String> values) {
        ensurePermissionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, permissions_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string permissions = 1;</code>
       */
      public Builder clearPermissions() {
        permissions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string permissions = 1;</code>
       */
      public Builder addPermissionsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePermissionsIsMutable();
        permissions_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList roles_ = emptyIntList();
      private void ensureRolesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          roles_ = mutableCopy(roles_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 roles = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getRolesList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(roles_) : roles_;
      }
      /**
       * <code>repeated int32 roles = 2;</code>
       */
      public int getRolesCount() {
        return roles_.size();
      }
      /**
       * <code>repeated int32 roles = 2;</code>
       */
      public int getRoles(int index) {
        return roles_.getInt(index);
      }
      /**
       * <code>repeated int32 roles = 2;</code>
       */
      public Builder setRoles(
          int index, int value) {
        ensureRolesIsMutable();
        roles_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 roles = 2;</code>
       */
      public Builder addRoles(int value) {
        ensureRolesIsMutable();
        roles_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 roles = 2;</code>
       */
      public Builder addAllRoles(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureRolesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, roles_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 roles = 2;</code>
       */
      public Builder clearRoles() {
        roles_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private int deptId_ ;
      /**
       * <code>int32 dept_id = 3;</code>
       */
      public int getDeptId() {
        return deptId_;
      }
      /**
       * <code>int32 dept_id = 3;</code>
       */
      public Builder setDeptId(int value) {
        
        deptId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dept_id = 3;</code>
       */
      public Builder clearDeptId() {
        
        deptId_ = 0;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 4;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 4;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 4;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object passwordEncrypted_ = "";
      /**
       * <code>string password_encrypted = 5;</code>
       */
      public java.lang.String getPasswordEncrypted() {
        java.lang.Object ref = passwordEncrypted_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          passwordEncrypted_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password_encrypted = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordEncryptedBytes() {
        java.lang.Object ref = passwordEncrypted_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          passwordEncrypted_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password_encrypted = 5;</code>
       */
      public Builder setPasswordEncrypted(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        passwordEncrypted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password_encrypted = 5;</code>
       */
      public Builder clearPasswordEncrypted() {
        
        passwordEncrypted_ = getDefaultInstance().getPasswordEncrypted();
        onChanged();
        return this;
      }
      /**
       * <code>string password_encrypted = 5;</code>
       */
      public Builder setPasswordEncryptedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        passwordEncrypted_ = value;
        onChanged();
        return this;
      }

      private int locked_ ;
      /**
       * <code>int32 locked = 6;</code>
       */
      public int getLocked() {
        return locked_;
      }
      /**
       * <code>int32 locked = 6;</code>
       */
      public Builder setLocked(int value) {
        
        locked_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 locked = 6;</code>
       */
      public Builder clearLocked() {
        
        locked_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:authUser.AuthUser)
    }

    // @@protoc_insertion_point(class_scope:authUser.AuthUser)
    private static final com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser();
    }

    public static com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AuthUser>
        PARSER = new com.google.protobuf.AbstractParser<AuthUser>() {
      @java.lang.Override
      public AuthUser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuthUser(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AuthUser> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuthUser> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.qianxun.grpc.lib.authUser.AuthUserOuterClass.AuthUser getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authUser_ByAccountReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authUser_ByAccountReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authUser_AuthUser_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authUser_AuthUser_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017auth_user.proto\022\010authUser\032\037google/prot" +
      "obuf/timestamp.proto\"\037\n\014ByAccountReq\022\017\n\007" +
      "account\030\001 \001(\t\"w\n\010AuthUser\022\023\n\013permissions" +
      "\030\001 \003(\t\022\r\n\005roles\030\002 \003(\005\022\017\n\007dept_id\030\003 \001(\005\022\n" +
      "\n\002id\030\004 \001(\005\022\032\n\022password_encrypted\030\005 \001(\t\022\016" +
      "\n\006locked\030\006 \001(\0052O\n\017AuthUserService\022<\n\014Get" +
      "ByAccount\022\026.authUser.ByAccountReq\032\022.auth" +
      "User.AuthUser\"\000B\037\n\035com.qianxun.grpc.lib." +
      "authUserP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_authUser_ByAccountReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_authUser_ByAccountReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authUser_ByAccountReq_descriptor,
        new java.lang.String[] { "Account", });
    internal_static_authUser_AuthUser_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_authUser_AuthUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authUser_AuthUser_descriptor,
        new java.lang.String[] { "Permissions", "Roles", "DeptId", "Id", "PasswordEncrypted", "Locked", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
