spring:
  application:
    name: qx-auth
  redis:
    password:
    host: 123.207.242.177
    timeout: 5000
  datasource:
    url: jdbc:mysql://123.207.242.177:3306/qx-test?useSSL=false&&serverTimezone=GMT%2B8
    username: root
    password: root
    #使用阿里的druid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# 直接放行URL
ignore:
  urls:
    - /actuator/**
    - /user/info/*
    - /log/**
    - /product/**

# 注册中心配置
eureka:
  instance:
    instance-id: qx-auth
    prefer-ip-address: true     #访问路径可以显示IP地址
  client:
    service-url:
      defaultZone: http://qx:qx@localhost:7001/eureka/
