spring:
  redis:
    password:
    host: 123.207.242.177
    timeout: 5000
  datasource:
    url: jdbc:mysql://123.207.242.177:3306/qx-test?useSSL=false&&serverTimezone=GMT%2B8
    username: root
    password: root
    #使用阿里的druid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# 直接放行URL
ignore:
  urls:
    - /actuator/**
    - /user/info/*
    - /log/**
    - /product/**
