// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_dept.proto

package com.qianxun.grpc.lib.dept;

public final class DeptProto {
  private DeptProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dept_DeptReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dept_DeptReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dept_DeptRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dept_DeptRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dept_UpdateDeptRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dept_UpdateDeptRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017grpc_dept.proto\022\004dept\032\037google/protobuf" +
      "/timestamp.proto\"\025\n\007DeptReq\022\n\n\002id\030\001 \001(\005\"" +
      "\271\001\n\007DeptRes\022\n\n\002id\030\001 \001(\005\022\021\n\tparent_id\030\002 \001" +
      "(\005\022\014\n\004sort\030\003 \001(\005\022.\n\ncreated_at\030\004 \001(\0132\032.g" +
      "oogle.protobuf.Timestamp\022.\n\nupdated_at\030\005" +
      " \001(\0132\032.google.protobuf.Timestamp\022\016\n\006stat" +
      "us\030\006 \001(\005\022\021\n\tdb_source\030\007 \001(\t\" \n\rUpdateDep" +
      "tRes\022\017\n\007success\030\001 \001(\0102\316\001\n\010GrpcDept\022)\n\007Ge" +
      "tDept\022\r.dept.DeptReq\032\r.dept.DeptRes\"\000\022/\n" +
      "\013GetDeptList\022\r.dept.DeptReq\032\r.dept.DeptR" +
      "es\"\0000\001\0222\n\nUpdateDept\022\r.dept.DeptRes\032\023.de" +
      "pt.UpdateDeptRes\"\000\0222\n\nDeleteDept\022\r.dept." +
      "DeptReq\032\023.dept.UpdateDeptRes\"\000B.\n\031com.qi" +
      "anxun.grpc.lib.deptB\tDeptProtoP\001\242\002\003RTGP\000" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_dept_DeptReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dept_DeptReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dept_DeptReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_dept_DeptRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dept_DeptRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dept_DeptRes_descriptor,
        new java.lang.String[] { "Id", "ParentId", "Sort", "CreatedAt", "UpdatedAt", "Status", "DbSource", });
    internal_static_dept_UpdateDeptRes_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dept_UpdateDeptRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dept_UpdateDeptRes_descriptor,
        new java.lang.String[] { "Success", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
