// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_dept.proto

package com.qianxun.grpc.lib.dept;

public interface DeptReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dept.DeptReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
