// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_dept.proto

package com.qianxun.grpc.lib.dept;

public interface DeptResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dept.DeptRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>int32 parent_id = 2;</code>
   */
  int getParentId();

  /**
   * <code>int32 sort = 3;</code>
   */
  int getSort();

  /**
   * <code>.google.protobuf.Timestamp created_at = 4;</code>
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 4;</code>
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp updated_at = 5;</code>
   */
  boolean hasUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updated_at = 5;</code>
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updated_at = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();

  /**
   * <code>int32 status = 6;</code>
   */
  int getStatus();

  /**
   * <code>string db_source = 7;</code>
   */
  java.lang.String getDbSource();
  /**
   * <code>string db_source = 7;</code>
   */
  com.google.protobuf.ByteString
      getDbSourceBytes();
}
