// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_dept.proto

package com.qianxun.grpc.lib.dept;

public interface UpdateDeptResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dept.UpdateDeptRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
