###################  项目启动端口  ###################
server:
  port: 8901
  servlet:
    context-path: /gen

###################  spring配置  ###################
spring:
  application:
    name: qx-generator
  datasource:
    url: jdbc:mysql://10.0.75.1:3306/qx-test?useSSL=false&&serverTimezone=GMT%2B8
    username: root
    password: root
    #使用阿里的druid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

###################  Mybatis配置  ###################
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml

# 注册中心配置
eureka:
  instance:
    instance-id: qx-generator-${server.port}
    # prefer-ip-address: true     #访问路径可以显示IP地址
    lease-renewal-interval-in-seconds: 3 #设置下线心跳
    lease-expiration-duration-in-seconds: 9
  client:
    service-url:
      defaultZone: http://qx:qx@10.0.75.1:7001/eureka/,http://qx:qx@10.0.75.1:7002/eureka/,http://qx:qx@10.0.75.1:7003/eureka/


