###################  项目启动端口  ###################
server:
  port: 8081
#  servlet:
#    context-path: /generator

###################  spring配置  ###################
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qx-test?useSSL=false&&serverTimezone=GMT%2B8
    username: root
    password: root
    #使用阿里的druid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

###################  Mybatis配置  ###################
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
